export default [
  {
    id: 'deco1',
    type: 'box',
    label: 'Business Service',
    height: 100,
    boundsIgnore: true,
    group: 'businessService',
  },
  {
    id: 'deco2',
    type: 'box',
    label: 'IT Service',
    height: 100,
    group: 'itService',
    boundsIgnore: true,
  },
  {
    id: 'deco3',
    type: 'box',
    label: 'Device Service',
    height: 100,
    group: 'deviceService',
    boundsIgnore: true,
  },
  {
    id: 'deco4',
    type: 'box',
    label: 'Application',
    height: 100,
    group: 'application',
    boundsIgnore: true,
  },
  {
    id: 'deco5',
    type: 'box',
    label: 'App Component',
    height: 100,
    group: 'applicationComponent',
    boundsIgnore: true,
  },
  {
    id: 'deco7',
    type: 'box',
    label: 'Device',
    height: 100,
    group: 'Device',
    boundsIgnore: true,
  },
  {
    id: 'deco8',
    type: 'box',
    label: 'Unknown',
    height: 100,
    group: 'Unknown',
    boundsIgnore: true,
  },
];
